version: '3'

services:
  bypass-cors-policies:
    image: miorey/bypass-cors-policies
    environment:
      - SERVER_NAME=https://play.blooket.com/play
    volumes:
      - ./storage:/usr/src/app/storage
    ports:
      - "3001:3000"
